version: "3"

services: 

  opentracing-example:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: opentracing-example
    env_file: .env
    networks: 
      - default
    ports:
      - 3000:3000
    depends_on: 
      - jaeger
      - psql_db
    volumes:
      - .:/go/src/github.com/Blackmocca/opentracing-example

  jaeger:
    image: jaegertracing/all-in-one:1.7@sha256:146de3a8c00e7ce536734d96627a71047d82481c4862ef79560a72dba1b4099a
    container_name: jaeger
    networks: 
      - default
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  psql_db:
    build:
      dockerfile: ./Dockerfile
      context: ./docker-script/postgres
    restart: always
    container_name: psql_db
    networks: 
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_example

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks: 
      - default
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: localdev