FROM golang:1.16

ARG app_name

RUN mkdir -p /go/src/github.com/Blackmocca/opentracing-example
WORKDIR /go/src/github.com/Blackmocca/opentracing-example

ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok


# Move to project folder
WORKDIR /go/src/github.com/Blackmocca/opentracing-example

COPY . . 
RUN go get -u github.com/githubnemo/CompileDaemon
RUN go mod tidy     

RUN  go build -o  /go/src/github.com/Blackmocca/opentracing-example/tmp/app main.go

EXPOSE 3000
EXPOSE 3100

ENTRYPOINT CompileDaemon -include=go.mod -log-prefix=false -color=true -build="go build -o ./tmp/app main.go" -command="./tmp/app" 
